### ISSUE TITLE
[Feature Request] Debugging Support for Mojo in VS Code and PyCharm

### ISSUE THREAD

**Issue by hkhk368** [modularml/mojo#1829]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

![image](https://github.com/modularml/mojo/assets/109432596/797cf23e-977c-4000-9aac-758cce255ac7)

I attempted to use breakpoints in VS Code for debugging, but the program did not pause at the breakpoint. I would like to inquire if it's possible to perform visual debugging with Mojo in either VS Code or PyCharm. If this feature is already available, could you please provide detailed instructions? I am a beginner in the Mojo language and have read through the following documentation, but it does not describe how to configure this: https://docs.modular.com/mojo/cli/debug.html.
Thank you.

### What is your motivation for this change?

This feature is very important for debugging.

### Any other details?

![image](https://github.com/modularml/mojo/assets/109432596/797cf23e-977c-4000-9aac-758cce255ac7)

I attempted to use breakpoints in VS Code for debugging, but the program did not pause at the breakpoint. I would like to inquire if it's possible to perform visual debugging with Mojo in either VS Code or PyCharm. If this feature is already available, could you please provide detailed instructions? I am a beginner in the Mojo language and have read through the following documentation, but it does not describe how to configure this: https://docs.modular.com/mojo/cli/debug.html.
Thank you.

**Comment by arthurevans** [comment]
This should be working in VS Code with 24.1 (make sure you have the 24.1 version of the extension, too).

https://docs.modular.com/mojo/tools/debugging

**Comment by hkhk368** [comment]
> This should be working in VS Code with 24.1 (make sure you have the 24.1 version of the extension, too).
> 
> https://docs.modular.com/mojo/tools/debugging

@arthurevans Thank you for your reply, but I have already installed the latest version 24.1. However, I am still unable to perform step-by-step debugging, and breakpoints are not being successfully hit. Please refer to the screenshot at the top. As soon as I click 'debug' to run, it directly outputs the result without pausing at the breakpoint.

**Comment by RtyLiu** [comment]
It works for me (VS Code):
<img width="820" alt="image" src="https://github.com/modularml/mojo/assets/93391555/8dd530af-7762-4c98-85b7-656cddf7481c">

**Comment by hkhk368** [comment]
> It works for me (VS Code): <img alt="image" width="820" src="https://private-user-images.githubusercontent.com/93391555/309333340-8dd530af-7762-4c98-85b7-656cddf7481c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTI5NjUsIm5iZiI6MTcwOTMxMjY2NSwicGF0aCI6Ii85MzM5MTU1NS8zMDkzMzMzNDAtOGRkNTMwYWYtNzc2Mi00Yzk4LTg1YjctNjU2Y2RkZjc0ODFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE3MDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYzM4MWZkNjYyNjdhMGFjOTA5M2RmNzA1NDAwNDM0ZWQ0ZDFlMjBmMGU5MTQ4NWI2Y2I4ODAwYmM2OGI0NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vkVZJCQcTfisdpw-tsyKprJ9jrkd5qLMpTB52aPnTQA">

@RtyLiu Thank you for sharing. My environment is Ubuntu 22.04. I have installed the latest version of VS Code and the Mojo 24.1 plugin. Have I missed anything?

**Comment by RtyLiu** [comment]
Is your VS Code Mojo extension v24.1.0?

**Comment by hkhk368** [comment]
> Is your VS Code Mojo extension v24.1.0?

Yes. But not working.

**Comment by RtyLiu** [comment]
Yes, you are right. I have tested and install it on another computer. The same Ubuntu, WSL 2, VS Code and Mojo extension for VS Code. It does not stop on breakpoint. The only difference is, that on the computer, where is working I have installed Mojo with Max . But I do not thing, that this the reason is.

**Comment by josiahls** [comment]
Getting a parallel issue with debugging via vscode. I get `personality set failed: Operation not permitted.`
It does corectly detect the debugger since I see "Welcome to Mojo debugging" but vscode still fails. 

Let me know if I should make a separate github issue. Posting it here as a comment since this is open still and generally related to vscode debugger supprot.

Mojo version is: mojo 24.2.1 (2f0dcf11) and the vscode extension is the same

![Screenshot from 2024-04-21 17-00-28](https://github.com/modularml/mojo/assets/19930483/919187b9-cac2-42f2-922f-7234430b9c70)

**Comment by lbartworks** [comment]
I see the same issue, not stopping at the right place, as well some crash messages on the debug console: 
sytem (Win 10, WSL 2, mojo 24.3)

i get this on a simple hello world program

error: JIT(0x7f98dfdd5000)(0x00007f98dfdd5000) The parsed MLIR structure type '!kgen.variant<struct<()>, scalar<bool>, scalar<si64>, scalar<f64>, struct<(pointer<none>, index)>, pointer<none>, pointer<none>, pointer<none>>' has not byte size. The MLIR type won't be used and regular MLIR-agnostic DWARF parsing will be performed.
error: JIT(0x7f98dfdd5000)(0x00007f98dfdd5000) [MojoDWARFParser::ParseTypeFromDWARF]: Unhandled type tag. Die = 0x403, tag = DW_TAG_variant_part, name = DW_TAG_variant_part
error: JIT(0x7f98dfdd5000)(0x00007f98dfdd5000) [MojoDWARFParser::CompleteTypeFromDWARF]: Couldn't complete the struct type '!kgen.variant<struct<()>, scalar<bool>, scalar<si64>, scalar<f64>, struct<(pointer<none>, index)>, pointer<none>, pointer<none>, pointer<none>>' because one of its fields has no size. Die = 0x3e9, member die = 0x3f0.
error: JIT(0x7f98dfdd5000)(0x00007f98dfdd5000) [MojoDWARFParser::CompleteTypeFromDWARF]: The struct type 'pkg stdlib::pkg builtin::module object::struct object' doesn't have the same size as reported in the DWARF after type completion. Die = 0x3d6.

**Comment by Ivo-Balbaert** [comment]
I have the same experience (in WSL Ubuntu on Windows 11): 
- No stop at breakpoints 
- Trying to get the value of a variable only gives:  
```
expression failed to parse (no further compiler diagnostics)
```
in the the graphical display for Variables or Watch, same in Debug Console.

**Comment by josiahls** [comment]
Note for those interested. This might be an issue with "remote/docker" environments:
- https://stackoverflow.com/questions/76939386/lldb-error-cannot-launch-a-out-personality-set-failed-operation-not-permitted
- https://github.com/llvm/llvm-project/issues/61899

One of the last blocks in my docker does:
```docker
RUN echo 'settings set target.disable-aslr false' > '/home/fastrl_mojo_user/.lldbinit'

Note max-nightly.path should be mojo.path if you're just using mojo

RUN BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" ) \
  && MOJO_PATH=$(modular config max-nightly.path) \ 
  && echo 'export MODULAR_HOME="'$HOME'/.modular"' >> "$BASHRC" \
  && echo 'export PATH="'$MOJO_PATH'/bin:$PATH"' >> "$BASHRC" \
  && echo 'export LLDBINIT=/home/fastrl_mojo_user/.lldbinit' >> "$BASHRC" \ 
  && source "$BASHRC"

```

**Comment by josiahls** [comment]
I think the mojo nightly extension doesn't actually have a working debugger.

I suspect it is trying to do `mojo-lldb tests/data/datapipes/base_test.mojo ` which is wrong. It doesn't look
like its possible to make the `launch.json` work correctly enough to make debugging via vscode possible.

Note the version ` mojo --version mojo 2024.8.305 (f99b2e40)`

```
fastrl_mojo_user@josiah-laptop:~/fastrl_mojo$ mojo-lldb tests/data/datapipes/base_test.mojo 
(lldb) target create "tests/data/datapipes/base_test.mojo"
error: '/home/fastrl_mojo_user/fastrl_mojo/tests/data/datapipes/base_test.mojo' is not a valid executable
(lldb) ^D
fastrl_mojo_user@josiah-laptop:~/fastrl_mojo$ mojo-lldb mojo tests/data/datapipes/base_test.mojo 
(lldb) target create "mojo"
Current executable set to '/home/fastrl_mojo_user/.modular/pkg/packages.modular.com_nightly_max/bin/mojo' (x86_64).
(lldb) settings set -- target.run-args  "tests/data/datapipes/base_test.mojo"
(lldb) r
Process 10797 launched: '/home/fastrl_mojo_user/.modular/pkg/packages.modular.com_nightly_max/bin/mojo' (x86_64)
Process 10797 stopped and restarted: thread 1 received signal: SIGCHLD
1
2
3
4
5
Process 10797 exited with status = 0 (0x00000000) 
(lldb) ^D
fastrl_mojo_user@josiah-laptop:~/fastrl_mojo$ mojo debug tests/data/datapipes/base_test.mojo 
Current executable set to '/home/fastrl_mojo_user/.modular/pkg/packages.modular.com_nightly_max/bin/mojo' (x86_64).
(lldb) r
Process 10941 launched: '/home/fastrl_mojo_user/.modular/pkg/packages.modular.com_nightly_max/bin/mojo' (x86_64)
Process 10941 stopped and restarted: thread 1 received signal: SIGCHLD
1
2
3
4
5

```

**Comment by aahrun** [comment]
> Getting a parallel issue with debugging via vscode. I get `personality set failed: Operation not permitted.` It does corectly detect the debugger since I see "Welcome to Mojo debugging" but vscode still fails.
> 
> Let me know if I should make a separate github issue. Posting it here as a comment since this is open still and generally related to vscode debugger support.
> 
> Mojo version is: mojo 24.2.1 (2f0dcf11) and the vscode extension is the same
> 
> Edit: Does not work for mojo 24.3.0 either

@josiahls has confirmed elsewhere that recent fixes to the extension resolved the specific separate issue mentioned above.
