### ISSUE TITLE
[BUG]: Trait implementation does not work since version 24.1

### ISSUE THREAD

**Issue by mzaks** [modularml/mojo#1858]
### Bug description

I get following error:

```
struct 'KeysContainer[KeyEndType]' does not implement all requirements for 'KeysBuilder'mojo
keys_container.mojo(22, 5): no 'add' candidates have type 'fn[DType, Int](self = inout $0, value = SIMD[*(0,0), *(0,1)]) -> None'
keys_container.mojo(71, 5): candidate declared here with type 'fn[DType, DType, Int](self = inout KeysContainer[*(0,0)], value = SIMD[*(0,1), *(0,2)]) -> None'
keys_container.mojo(23, 5): no 'add_buffer' candidates have type 'fn[DType](self = inout $0, pointer = DTypePointer[*(0,0), 0], size = Int) -> None'
keys_container.mojo(92, 5): candidate declared here with type 'fn[DType, DType](self = inout KeysContainer[*(0,0)], pointer = DTypePointer[*(0,1), 0], size = Int) -> None'
keys_container.mojo(21, 1): trait 'KeysBuilder' declared here
```

### Steps to reproduce

Code snippet:
```
trait KeysBuilder:
    fn add[T: DType, size: Int](inout self, value: SIMD[T, size]): ...
    fn add_buffer[T: DType](inout self, pointer: DTypePointer[T], size: Int): ...

struct KeysContainer[KeyEndType: DType = DType.uint32](Sized, KeysBuilder):
    fn add[T: DType, size: Int](inout self, value: SIMD[T, size]): pass
    fn add_buffer[T: DType](inout self, pointer: DTypePointer[T], size: Int): pass
    fn __len__(self) -> Int: pass
```

Full example can be found in [here](https://github.com/mzaks/compact-dict/blob/main/generic_dict/keys_container.mojo)

### System information

```shell
macOS 14.2.1 (23C71) macMini M1
mojo 24.1.0 (55ec12d6)
modular 0.4.1 (2d8afe15)
```

**Comment by lattner** [comment]
@Mogball can you take a look at this when you get a chance?  It's a regression and Maxim is building really cool stuff that I want to make sure stays unblocked :)

**Comment by lattner** [comment]
Here's an even more reduced testcase:

```
trait KeysBuilder:
    fn add[T: DType](inout self): ...

struct KeysContainer[KeyEndType: DType](KeysBuilder):
    fn add[T: DType](inout self):
      pass
```
which yields:
```
t.mojo:5:8: error: struct 'KeysContainer[KeyEndType]' does not implement all requirements for 'KeysBuilder'
struct KeysContainer[KeyEndType: DType](KeysBuilder):
       ^
t.mojo:2:8: note: no 'add' candidates have type 'fn[DType](self = inout $0) -> None'
    fn add[T: DType](inout self): ...
       ^
t.mojo:6:8: note: candidate declared here with type 'fn[DType, DType](self = inout KeysContainer[*(0,0)]) -> None'
    fn add[T: DType](inout self):
       ^
t.mojo:1:7: note: trait 'KeysBuilder' declared here
trait KeysBuilder:
      ^
```

It looks like parameter checking in conformance checking isn't skipping over the parameters of the container.  speculation: This might be related to some of the internal changes @laszlokindrat made?

**Comment by Mogball** [comment]
Should be fixed in the next release

**Comment by mzaks** [comment]
@Mogball I just checked release 24.1.1 the bug is still present

**Comment by arthurevans** [comment]
It appears that cherry-picking the fix into 24.1.1 was not feasible but we missed updating this issue. This should be fixed in the upcoming 24.2.
