### ISSUE TITLE
[BUG] [LSP] stderr logs have invalid encoding

### ISSUE THREAD

**Issue by dmitry-salin** [modularml/mojo#2835]
### Bug description

Nightly versions of `mojo-lsp-server` produce stderr logs with invalid encoding.
This, for example, makes lsp unusable in Helix editor. It requires the lsp output to be valid UTF-8. It's very likely that changes to this behavior will not be accepted since the problem only occurs with Mojo lsp.

Release version mojo 24.3.0 (9882e19d) does not have this problem and works correctly with Helix.

### Steps to reproduce

stderr `mojo-lsp-server` logs in VS Code

![mojo_lsp_stderr](https://uploads.linear.app/2f794fde-0e09-4092-aa52-1ed3e9241f74/6f370e83-b480-431b-b066-dc172768c397/128bedcd-9c89-4060-8848-9fe2521b4fd1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzJmNzk0ZmRlLTBlMDktNDA5Mi1hYTUyLTFlZDNlOTI0MWY3NC82ZjM3MGU4My1iNDgwLTQzMWItYjA2Ni1kYzE3Mjc2OGMzOTcvMTI4YmVkY2QtOWM4OS00MDYwLTg4NDgtOWZlMjUyMWI0ZmQxIiwiaWF0IjoxNzE2OTMyOTk2LCJleHAiOjMzMjg3NDkyOTk2fQ.OAKht7HI-jiC9npkMsDp6HT4mg-RVn0XEyyu-xvIJeY)

Example of stderr `mojo-lsp-server` buffer in Helix:

```
[
    73, 91, 49, 53, 58, 48, 50, 58, 52, 54, 46, 52, 53, 54, 93, 32, 45, 45, 62, 32, 114, 101,
    112, 108, 121, 58, 193, 94, 232, 88, 195, 86, 0, 0, 109, 101, 110, 116, 47, 100, 101, 102,
    105, 110, 105, 116, 105, 111, 110, 40, 49, 41, 10, 68, 91, 49, 53, 58, 48, 50, 58, 52, 54,
    46, 52, 53, 54, 93, 32, 62, 62, 62, 32, 123, 34, 105, 100, 34, 58, 49, 44, 34, 106, 115,
    111, 110, 114, 112, 99, 34, 58, 34, 50, 46, 48, 34, 44, 34, 114, 101, 115, 117, 108, 116,
    34, 58, 91, 123, 34, 114, 97, 110, 103, 101, 34, 58, 123, 34, 101, 110, 100, 34, 58, 123,
    34, 99, 104, 97, 114, 97, 99, 116, 101, 114, 34, 58, 49, 50, 44, 34, 108, 105, 110, 101,
    34, 58, 49, 125, 44, 34, 115, 116, 97, 114, 116, 34, 58, 123, 34, 99, 104, 97, 114, 97, 99,
    116, 101, 114, 34, 58, 55, 44, 34, 108, 105, 110, 101, 34, 58, 49, 125, 125, 44, 34, 117,
    114, 105, 34, 58, 34, 102, 105, 108, 101, 58, 47, 47, 47, 104, 111, 109, 101, 47, 100, 109,
    105, 116, 114, 121, 47, 116, 109, 112, 47, 109, 111, 106, 111, 47, 116, 101, 115, 116, 46,
    109, 111, 106, 111, 34, 125, 93, 125, 10, 10,
]
```

It can be decoded as Latin-1 (8859-1), but I think that is not what was intended:

```
I[15:02:46.456] --> reply:Á^èXÃVment/definition(1)
D[15:02:46.456] >>> {"id":1,"jsonrpc":"2.0","result":[{"range":{"end":{"character":12,"line":1},"start":{"character":7,"line":1}},"uri":"file:///home/dmitry/tmp/mojo/test.mojo"}]}
```

It seems it should be like this: `I[15:02:46.456] --> reply:textDocument/definition(1)`

### System information

```shell
Pop!_OS 22.04 LTS
mojo 2024.5.2505 (08130894)
```

**Comment by walter-erquinigo** [comment]
This should have been fixed already. Thank for your reporting it. I forgot to give you the credit you deserve :)

**Comment by krobelus** [comment]
How can I upgrade to a fixed version? I'm still seeing this on

```
$ modular list-packages
  mojo @ 24.4.0 : /home/johannes/.modular/pkg/packages.modular.com_mojo
```

**Comment by walter-erquinigo** [comment]
We've moved away from the `modular` tool. You should be using `magic` and `max`. https://docs.modular.com/magic/
