### ISSUE TITLE
[BUG] Divergences in Standard Library naming conventions

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#309]
### Bug description

```shell
Python has a lot of problems left over from the previous era connected to naming which cannot be fixed due to compatibility reasons. Mojo as new language should has unified convention but it does the same divergences as Python in Testing and instead of snake_case for methods it uses camelCase:
- assertEqual
- assertAlmostEqual

Mojo has a great opportunity to fix that problems and be consistent in naming convention, so:
- assertEqual should be assert_equal
- assertAlmostEqual should be assert_almost_equal etc.
```

### Steps to reproduce

```shell
-
```

**Comment by elisbyberi** [comment]
@gryznar The [unittest](https://docs.python.org/3/library/unittest.html#module-unittest) unit testing framework was originally inspired by JUnit. I don't believe it will change in the future, and it's not ideal to deviate from the [xUnit](https://en.wikipedia.org/wiki/XUnit) unit testing framework family.

**Comment by gryznar** [comment]
I see, but this is very unpythonic and I do not see the point why Mojo can't just have done it a better way. I am aware that it was inspired by java-like style but it is the source of truth for it? It seems very odd, that a lot of things  in Python heavily inspired by other language has snake_case or PascalCase style which is consistent and only testing or logging library has not.

**Comment by elisbyberi** [comment]
@gryznar Quoting from [Why Mojo](https://docs.modular.com/mojo/why-mojo.html#a-member-of-the-python-family:~:text=Further%2C%20we%20decided%20that%20the%20right%20long%2Dterm%20goal%20for%20Mojo%20is%20to%20provide%20a%20superset%20of%20Python%20(that%20is%2C%20to%20make%20Mojo%20compatible%20with%20existing%20Python%20programs)%20and%20to%20embrace%20the%20CPython%20implementation%20for%20long%2Dtail%20ecosystem%20support.):

> _Further, we decided that the right long-term goal for Mojo is to provide a **superset of Python** (that is, to make Mojo compatible with existing Python programs) and to embrace the CPython implementation for long-tail ecosystem support._

Supporting the Python Standard Library is crucial.

**Comment by gryznar** [comment]
But Testing is Mojo's library, not Python's, so what's the point here? Sorry, I don't understand this point

**Comment by elisbyberi** [comment]
@gryznar Mojo's long-term goal is to achieve compatibility with existing Python programs, e.g., running a Python unittest in Mojo without relying on CPython.

While it is beneficial to adhere to Python PEP 8 (though not mandatory), it's worth noting that Mojo currently does not have any specific naming convention.

**Comment by gryznar** [comment]
But that's not the case of compatibility. In Python there is:
`unittest.TestCase.assertEqual`
In Mojo:
`Testing.TestSuite.asssertEqual`
so, there is technical obstacles to have:
`unittest.TestCase.assertEqual` (bind to CPython  somehow) and `Testing.TestSuite.asssert_equal`

**Comment by gryznar** [comment]
I have open a topic on Python ideas to just give a feedback what Python developers could do if they would have the possibility  to start unittest from scratch: https://discuss.python.org/t/snake-case-aliases-to-camelcased-methods-in-unittest/27381/4 and I got this answer from Core Python developer:
![image](https://github.com/modularml/mojo/assets/90425096/a0681657-27d7-474b-a344-f52ce8ea80a4)

Mojo is in this place, where it can change it within its own Testing.TestSuite struct.

**Comment by lattner** [comment]
You're right, we haven't been very careful with the definition of api's and auditing their names etc, we should fix them to be consistent.  @abduld can you ask someone to fix these up?  Thx

**Comment by abduld** [comment]
Yes, we are in the process of auditing the names and making sure they are more closely aligned with Python

**Comment by gryznar** [comment]
2 weeks have passed and this trivial fix is still not implemented unfortunately :(

**Comment by abduld** [comment]
sorry, but we do want python naming compatibility in this case. It's unfortunate that python did not follow the snake case convention here

**Comment by gryznar** [comment]
I have posted a screenshot with statement from Core Python developer which says, that if they just have occasion to choose one more time, they would choose snake case. It is that not enough?

**Comment by elisbyberi** [comment]
> sorry, but we do want python naming compatibility in this case. It's unfortunate that python did not follow the snake case convention here

It's because unittest predates PEP8. https://peps.python.org/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds

**Comment by gryznar** [comment]
If someone would like to use Python code directly in Mojo, he cannot just copy-paste existing tests. He has to adjust inheritance and import : unittest ->Testing and TestCase -> TestSuite, so what is the problem to adjust also assertions and get rid off this awful camelCase here?

**Comment by elisbyberi** [comment]
@gryznar Two notable aspects are search friendliness and method overloading. For example, you can easily search using a single method name like "assertEqual". When dealing with thousands of pages of documentation and millions of lines of code, CTRL+F becomes your closest ally.

**Comment by gryznar** [comment]
If someone would like to use Python unittest  he can just import unittest. That's not the point here. A lot of custom methods in Mojo will have different name than in Python.

**Comment by gryznar** [comment]
Searching for methods happens only few times. This is not repeatable process. If someone would search for phrase: "assert" the result will point both to assertEqual and to assert_equal. Python users in most cases are using pyteat and not legacy unittest.

**Comment by gryznar** [comment]
People in most cases would appreciate Mojo, that incosistent name are fixed.

**Comment by gryznar** [comment]
Here I've posted all arguments: https://github.com/modularml/mojo/discussions/384

**Comment by abduld** [comment]
it looks like the way forward is to not pretend that the Mojo testing is compatible with Python testing package and consistently use snake case. I am not against that @gryznar and thanks for raising this

**Comment by gryznar** [comment]
@abduld assertFalse is still to fix:
![image](https://github.com/modularml/mojo/assets/90425096/2c788b5c-b275-41fc-a64f-d2762f32d18e)

**Comment by abduld** [comment]
Ah, yes sorry missed that as part of the rename

**Comment by gryznar** [comment]
No problem :) If you would like to get used to snake_case, there is also separate issue to fix that convention in documentation. :)
