### ISSUE TITLE
[BUG] mojo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by mojo)

### ISSUE THREAD

**Issue by notnot** [modularml/mojo#3684]
### Bug description

I tried to install mojo by following the "Get Started with Mojo" page. Installing Magic seems to have worked, but mojo then gives these errors:

(hello-world) jpad@boxob:~/.../mojo/hello-world$ magic shell
 . "/tmp/pixi_env_dIC.sh"
jpad@boxob:~/.../mojo/hello-world$  . "/tmp/pixi_env_dIC.sh"
(hello-world) jpad@boxob:~/.../mojo/hello-world$ mojo
mojo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by mojo)
mojo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by mojo)
mojo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by mojo)
mojo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/jpad/prog/mojo/hello-world/.magic/envs/default/bin/../lib/libAsyncRTRuntimeGlobals.so)

I'm on an ubuntu 20.04 system, which should be fine according to (not so recent) system requirements for mojo that i have seen.
Is there a fix? I'm eager to try out this new programming language, so it's annoying to see it fail in this very early stage :(
 

### Steps to reproduce

Just follow the instructions at https://docs.modular.com/mojo/manual/get-started on an unbuntu 20.04 machine.

### System information

```shell
- What OS did you do install Mojo on ?
Ubuntu 20.04

- Provide version information for Mojo by pasting the output of `mojo -v`
Can't provide the version because mojo returns the 'glibc version not found' error first.

- Provide Magic CLI version by pasting the output of `magic -V` or `magic --version` 
magic 0.3.1 - (based on pixi 0.29.0)

- Optionally, provide more information with `magic info`.
      Pixi version: 0.29.0
          Platform: linux-64
  Virtual packages: __unix=0=0
                  : __linux=5.15.0=0
                  : __glibc=2.31=0
                  : __cuda=12.2=0
                  : __archspec=1=skylake
         Cache dir: /home/jpad/.cache/rattler/cache
      Auth storage: /home/jpad/.rattler/credentials.json
  Config locations: No config files found

Project
------------
              Name: hello-world
           Version: 0.1.0
     Manifest file: /home/jpad/prog/mojo/hello-world/mojoproject.toml
      Last updated: 17-10-2024 01:01:09

Environments
------------
       Environment: default
          Features: default
          Channels: conda-forge, https://conda.modular.com/max
  Dependency count: 1
      Dependencies: max
  Target platforms: linux-64
```

**Comment by hermanthotan** [comment]
I also encounter the same issue
sudo apt update
sudo apt upgrade libc6

still not working

**Comment by notnot** [comment]
Solved by upgrading to Ubuntu 22.04, but ideally it should work on 20.04 as well, I’m still a proponent of that as I know there are still many older machines around…

**Comment by hermanthotan** [comment]
I have un-install my old ubuntu and install Ubuntu 20.04.06 LTS from Windows Store, still showing the same error
![image](https://github.com/user-attachments/assets/88c445cf-f91b-43f7-8db8-57ec226f2803)

mojo --version
mojo which

throw the above error.

**Comment by f0cii** [comment]
Hey there! here’s a quick fix for you:

First, let’s open up the sources list. Just run:
bash
sudo nano /etc/apt/sources.list
Add this line at the end of the file:
```
deb http://th.archive.ubuntu.com/ubuntu jammy main
```

then
sudo apt update
Next, upgrade the libc6 package.

sudo apt install libc6
or
sudo apt upgrade

Also, make sure to install these additional packages:
sudo apt-get install zlib1g-dev libtinfo-dev

strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
You should see a list of GLIBCXX versions like this:
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_DEBUG_MESSAGE_LENGTH

After doing all this, I tried it out, and it worked great on Ubuntu 20.04! Hope this helps you too!

**Comment by bellaj** [comment]
Thanks @f0cii ! it helped

**Comment by cprepos** [comment]
@f0cii you beautiful, beautiful person. Thank you so much, worked like a charm.

**Comment by conorbronsdon** [comment]
Status update on this one. The [Mojo system requirements](https://docs.modular.com/mojo/requirements/) now list Ubuntu 22.04 LTS as the minimum supported Linux distribution. Ubuntu 20.04 ships glibc 2.31, which is below what Mojo requires (2.32+). There are no current plans to lower the glibc floor that I'm aware of, though one of the Mojo team can feel free to chime in and correct me. 

If upgrading your host OS isn't an option, the workaround @f0cii shared earlier in this thread (pulling glibc from the jammy repo) is the best path, great call. For a fresh setup, the [getting started guide](https://docs.modular.com/mojo/manual/get-started/) covers the supported path.

Leaving this open as a reference for anyone hitting the same error. We'll update later if we make adjustments to requirements.

**Comment by kerberjg** [comment]
@f0cii unfortunately this breaks other packages, for example I can't install `gstreamer1.0-plugins-good` anymore: 

```
The following packages have unmet dependencies:
 gstreamer1.0-plugins-good : Depends: libgdk-pixbuf-2.0-0 (>= 2.22.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
