### ISSUE TITLE
[BETA][BUG] Cannot return memory-primary types in tuples

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#516]
### Bug description

Returning tensors seems to fail.

### Steps to reproduce

```
from tensor import Tensor

fn may_i_have_a_tuple_of_tensor() -> (Tensor[DType.float32], Tensor[DType.uint32]):
    return (Tensor[DType.float32](100, 3), Tensor[DType.uint32](100, 3))

let a: Tensor[DType.float32]
let b: Tensor[DType.uint32]
a, b = may_i_have_a_tuple_of_tensor()
```
outputs
```
error: Expression [8]:24:6: invalid call to 'get': result cannot bind generic !mlirtype to memory-only type 'Tensor[f32]'
    a, b = may_i_have_a_tuple_of_tensor()
    ~^~~

Expression [0]:1:1: function declared here
from memory.unsafe import Pointer
^

expression failed to parse (no further compiler diagnostics)
```

changing it to
```
let a,b = may_i_have_a_tuple_of_tensor()
```
outputs:
```
error: Expression [9]:22:5: declaration must have either a type or an initializer
    let a, b = may_i_have_a_tuple_of_tensor()
````

**Comment by Mogball** [comment]
Thanks for the bug report! We're still figuring out the ins and outs of how tuple support will work, especially for memory-only types.

**Comment by lattner** [comment]
Is this fixed in 0.6?

**Comment by Mogball** [comment]
I don't believe so

**Comment by gabrieldemarmiesse** [comment]
There was a more recent issue about this that I opened: https://github.com/modularml/mojo/issues/1817 . The bug is still here as of v2024.1.0. We might want to deduplicate issues and close one of those two.

**Comment by lattner** [comment]
Fixed in the next release.
