### ISSUE TITLE
[Modular CLI]: Ensure proper bugtracker link is used

### ISSUE THREAD

**Issue by asl** [modularml/mojo#803]
### Issue description

See as and example: https://github.com/llvm/llvm-project/issues/66440

Unrelated mojo issue is reported to wrong (LLVM) bugtracker

### Steps to reproduce

See https://github.com/llvm/llvm-project/issues/66440

### Version Info

```shell
See https://github.com/llvm/llvm-project/issues/66440
```

**Comment by carusyte** [comment]
Seems this gist could help
https://gist.github.com/trevorhobenshield/6bca58f947ad6115a113a97072df1a73

**Comment by bzcheeseman** [comment]
This is fixed and will be in the next release.

**Comment by asl** [comment]
Another reported issue to wrong bugtracker due to this: https://github.com/llvm/llvm-project/issues/67246

**Comment by asl** [comment]
Looks like still an issue: https://github.com/llvm/llvm-project/issues/70558

**Comment by asl** [comment]
@bzcheeseman Still an issue? See https://github.com/llvm/llvm-project/issues/82105

**Comment by bzcheeseman** [comment]
Hey sorry, I'm not actually sure! @smuniraj2018 or @zbowling will be able to help you here.

**Comment by lattner** [comment]
@River707 potentially as well.

**Comment by River707** [comment]
Thanks, I thought we fixed that... I'll take a look after holiday

**Comment by River707** [comment]
Hmm, we should already be setting the bug report on the [modular](https://github.com/modularml/modular/blob/cedecef47319e30411016923924a93d1382f163e/All/tools/modular/modular.cpp#L49) tool (and [mojo](https://github.com/modularml/modular/blob/cedecef47319e30411016923924a93d1382f163e/KGEN/tools/mojo/mojo.cpp#L51))
